# Generated by Django 4.2.2 on 2023-11-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0003_youtubecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecontent',
            name='category',
            field=models.TextField(choices=[('Classroom Management', 'Classroom Management'), ('Technology Integration', 'Technology Integration'), ('Assessment and Feedback', 'Assessment and Feedback'), ('Parents Engagement', 'Parents Engagement'), ('Students Engagement', 'Students Engagement'), ('Inclusion', 'Inclusion'), ('Real-world skills', 'Real-world skills')], null=True),
        ),
    ]
