# Generated by Django 4.2.2 on 2023-12-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0006_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='takeaways',
            field=models.TextField(null=True),
        ),
    ]
