# Generated by Django 4.2.2 on 2023-12-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0007_resources_takeaways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='takeaways',
            field=models.TextField(default=''),
        ),
    ]
