# Generated by Django 4.2.2 on 2023-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0008_alter_resources_takeaways'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='takeaways',
        ),
        migrations.AddField(
            model_name='youtubecontent',
            name='takeaways',
            field=models.TextField(default=''),
        ),
    ]
