# Generated by Django 5.1.2 on 2024-10-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0009_remove_resources_takeaways_youtubecontent_takeaways'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('source', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
