# Generated by Django 5.1.2 on 2024-10-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascend', '0010_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
